function execute() {
    return Response.success([
        { title: "Hệ Thống", input: "https://truyen35.vn/the-loai/he-thong", script: "gen.js" },
        { title: "Kiếm Hiệp", input: "https://truyen35.vn/the-loai/kiem-hiep", script: "gen.js" },
        { title: "Tiên Hiệp", input: "https://truyen35.vn/the-loai/tien-hiep", script: "gen.js" },
        { title: "Ngôn Tình", input: "https://truyen35.vn/the-loai/ngon-tinh-35nb", script: "gen.js" },
        { title: "Đam Mỹ", input: "https://truyen35.vn/the-loai/dam-my", script: "gen.js" },
        { title: "Bách Hợp", input: "https://truyen35.vn/the-loai/bach-hop", script: "gen.js" },
        { title: "Xuyên Không", input: "https://truyen35.vn/the-loai/xuyen-khong", script: "gen.js" },
        { title: "Xuyên Nhanh", input: "https://truyen35.vn/the-loai/xuyen-nhanh", script: "gen.js" },
        { title: "Huyền Huyễn", input: "https://truyen35.vn/the-loai/huyen-huyen", script: "gen.js" },
        { title: "Cung Đấu", input: "https://truyen35.vn/the-loai/cung-dau", script: "gen.js" },
        { title: "Cổ Đại", input: "https://truyen35.vn/the-loai/co-dai", script: "gen.js" },
        { title: "Đô Thị", input: "https://truyen35.vn/the-loai/do-thi", script: "gen.js" },
        { title: "Sắc", input: "https://truyen35.vn/the-loai/sac", script: "gen.js" },
        { title: "Sủng", input: "https://truyen35.vn/the-loai/sung", script: "gen.js" },
        { title: "Ngược", input: "https://truyen35.vn/the-loai/nguoc", script: "gen.js" },
        { title: "Dị Giới", input: "https://truyen35.vn/the-loai/di-gioi", script: "gen.js" },
        { title: "Dị Năng", input: "https://truyen35.vn/the-loai/di-nang", script: "gen.js" },
        { title: "Linh Dị", input: "https://truyen35.vn/the-loai/linh-di", script: "gen.js" },
        { title: "Hài Hước", input: "https://truyen35.vn/the-loai/hai-huoc", script: "gen.js" },
        { title: "Nữ Hiệp", input: "https://truyen35.vn/the-loai/nu-hiep", script: "gen.js" },
        { title: "Nữ Cường", input: "https://truyen35.vn/the-loai/nu-cuong", script: "gen.js" },
        { title: "Nữ Phụ", input: "https://truyen35.vn/the-loai/nu-phu", script: "gen.js" },
        { title: "Trinh Thám", input: "https://truyen35.vn/the-loai/trinh-tham", script: "gen.js" },
        { title: "Truyện Ma", input: "https://truyen35.vn/the-loai/truyen-ma", script: "gen.js" },
        { title: "Lịch Sử", input: "https://truyen35.vn/the-loai/lich-su", script: "gen.js" },
        { title: "Quân Sự", input: "https://truyen35.vn/the-loai/quan-su", script: "gen.js" },
        { title: "Mạt Thế", input: "https://truyen35.vn/the-loai/mat-the", script: "gen.js" },
        { title: "Võng Du", input: "https://truyen35.vn/the-loai/vong-du", script: "gen.js" },
        { title: "Trọng Sinh", input: "https://truyen35.vn/the-loai/trong-sinh", script: "gen.js" },
        { title: "Truyện Teen", input: "https://truyen35.vn/the-loai/truyen-teen", script: "gen.js" },
        { title: "Light Novel", input: "https://truyen35.vn/the-loai/light-novel", script: "gen.js" },
        { title: "Điền Văn", input: "https://truyen35.vn/the-loai/dien-van", script: "gen.js" },
        { title: "Thám Hiểm", input: "https://truyen35.vn/the-loai/tham-hiem", script: "gen.js" },
        { title: "Tiểu thuyết", input: "https://truyen35.vn/the-loai/tieu-thuyet", script: "gen.js" },
    ]);
}
