function execute() {
    return Response.success([
        { title: "Kỳ Huyễn Tây Phương",   input: "1",  script: "genrecontent.js" },
        { title: "Tiên Hiệp Đông Phương",  input: "2",  script: "genrecontent.js" },
        { title: "Khoa Huyễn Tận Thế",     input: "3",  script: "genrecontent.js" },
        { title: "Đô Thị Nhật Thường",     input: "4",  script: "genrecontent.js" },
        { title: "Tu Chân Đô Thị",         input: "5",  script: "genrecontent.js" },
        { title: "Cao Vũ Đô Thị",          input: "6",  script: "genrecontent.js" },
        { title: "Lịch Sử Cổ Đại",         input: "7",  script: "genrecontent.js" },
        { title: "Chiến Thần",             input: "8",  script: "genrecontent.js" },
        { title: "Điền Văn Đô Thị",        input: "9",  script: "genrecontent.js" },
        { title: "Huyền Huyễn",            input: "10", script: "genrecontent.js" },
        { title: "Lịch Sử Sáng Tạo",       input: "11", script: "genrecontent.js" },
        { title: "Trinh Thám Sáng Tạo",    input: "12", script: "genrecontent.js" },
        { title: "Đô Thị Sáng Tạo",        input: "13", script: "genrecontent.js" },
        { title: "Huyền Huyễn Sáng Tạo",   input: "14", script: "genrecontent.js" },
        { title: "Linh Dị Trinh Thám",      input: "15", script: "genrecontent.js" },
        { title: "Gián Điệp Kháng Chiến",  input: "16", script: "genrecontent.js" },
        { title: "Game Thể Thao",          input: "17", script: "genrecontent.js" },
        { title: "Manga Anime",            input: "18", script: "genrecontent.js" },
        { title: "Nam Tần Phái Sinh",       input: "19", script: "genrecontent.js" },
        { title: "Cổ Phong",               input: "20", script: "genrecontent.js" },
        { title: "Nữ Tần Phái Sinh",        input: "21", script: "genrecontent.js" },
        { title: "Huyền Huyễn Ngôn Tình",  input: "22", script: "genrecontent.js" },
        { title: "Điền Văn",               input: "23", script: "genrecontent.js" },
        { title: "Niên Đại",               input: "24", script: "genrecontent.js" },
        { title: "Hiện Đại Sáng Tạo",      input: "25", script: "genrecontent.js" },
        { title: "Cung Đấu",               input: "26", script: "genrecontent.js" },
        { title: "Cổ Ngôn Sáng Tạo",       input: "27", script: "genrecontent.js" },
        { title: "Xuyên Nhanh",            input: "28", script: "genrecontent.js" },
        { title: "Thanh Xuân Ngọt Ngào",   input: "29", script: "genrecontent.js" },
        { title: "Showbiz",                input: "30", script: "genrecontent.js" },
        { title: "Nữ Tần Trinh Thám",       input: "31", script: "genrecontent.js" },
        { title: "Hôn Nhân Nghề Nghiệp",   input: "32", script: "genrecontent.js" },
        { title: "Hào Môn Tổng Tài",        input: "33", script: "genrecontent.js" },
        { title: "Dân Quốc Ngôn Tình",     input: "34", script: "genrecontent.js" },
        { title: "Sách Xuất Bản",           input: "36", script: "genrecontent.js" }
    ]);
}
