function execute() {
    return Response.success([
        { title: "Bách hợp", input: "https://chatxam.info/genre/bach-hop/", script: "gen.js" },
        { title: "Bán nón", input: "https://chatxam.info/genre/ban-non/", script: "gen.js" },
        { title: "Băng luyến", input: "https://chatxam.info/genre/bang-luyen/", script: "gen.js" },
        { title: "Cảnh hoa", input: "https://chatxam.info/genre/canh-hoa/", script: "gen.js" },
        { title: "Cao H", input: "https://chatxam.info/genre/cao-h/", script: "gen.js" },
        { title: "Cha con gái", input: "https://chatxam.info/genre/cha-con-gai/", script: "gen.js" },
        { title: "Chân khống", input: "https://chatxam.info/genre/chan-khong/", script: "gen.js" },
        { title: "Công - Tức", input: "https://chatxam.info/genre/cong-tuc/", script: "gen.js" },
        { title: "Cưỡng gian", input: "https://chatxam.info/genre/cuong-gian/", script: "gen.js" },
        { title: "Dâm hiệp", input: "https://chatxam.info/genre/dam-hiep/", script: "gen.js" },
        { title: "Dị thế", input: "https://chatxam.info/genre/di-the/", script: "gen.js" },
        { title: "Điều giáo", input: "https://chatxam.info/genre/dieu-giao/", script: "gen.js" },
        { title: "Đô thị", input: "https://chatxam.info/genre/do-thi/", script: "gen.js" },
        { title: "Đồng nhân", input: "https://chatxam.info/genre/dong-nhan/", script: "gen.js" },
        { title: "Hậu cung", input: "https://chatxam.info/genre/hau-cung/", script: "gen.js" },
        { title: "Hệ thống", input: "https://chatxam.info/genre/he-thong/", script: "gen.js" },
        { title: "Họ hàng", input: "https://chatxam.info/genre/ho-hang/", script: "gen.js" },
        { title: "Huynh muội", input: "https://chatxam.info/genre/huynh-muoi/", script: "gen.js" },
        { title: "Loạn luân", input: "https://chatxam.info/genre/loan-luan/", script: "gen.js" },
        { title: "Mẫu tử - mẹ con", input: "https://chatxam.info/genre/mau-tu/", script: "gen.js" },
        { title: "Ngôn tình", input: "https://chatxam.info/genre/ngon-tinh/", script: "gen.js" },
        { title: "Nhân thê", input: "https://chatxam.info/genre/nhan-the/", script: "gen.js" },
        { title: "Nón xanh", input: "https://chatxam.info/genre/non-xanh/", script: "gen.js" },
        { title: "Quan trường", input: "https://chatxam.info/genre/quan-truong/", script: "gen.js" },
        { title: "Sắc hiệp", input: "https://chatxam.info/genre/sac-hiep/", script: "gen.js" },
        { title: "SM", input: "https://chatxam.info/genre/sm/", script: "gen.js" },
        { title: "Sư đồ", input: "https://chatxam.info/genre/su-do/", script: "gen.js" },
        { title: "Tất chân", input: "https://chatxam.info/genre/tat-chan/", script: "gen.js" },
        { title: "Thôi miên", input: "https://chatxam.info/genre/thoi-mien/", script: "gen.js" },
        { title: "Thuần yêu", input: "https://chatxam.info/genre/thuan-yeu/", script: "gen.js" },
        { title: "Thục phụ", input: "https://chatxam.info/genre/thuc-phu/", script: "gen.js" },
        { title: "Tiên hiệp", input: "https://chatxam.info/genre/tien-hiep/", script: "gen.js" },
        { title: "Trọng sinh", input: "https://chatxam.info/genre/trong-sinh/", script: "gen.js" },
        { title: "Trường học", input: "https://chatxam.info/genre/truong-hoc/", script: "gen.js" },
        { title: "Tu tiên", input: "https://chatxam.info/genre/tu-tien/", script: "gen.js" },
        { title: "Tỷ đệ", input: "https://chatxam.info/genre/ty-de/", script: "gen.js" },
        { title: "Viễn tưởng", input: "https://chatxam.info/genre/vien-tuong/", script: "gen.js" },
        { title: "Võ hiệp", input: "https://chatxam.info/genre/vo-hiep/", script: "gen.js" },
        { title: "Xanh mẫu", input: "https://chatxam.info/genre/xanh-mau/", script: "gen.js" },
        { title: "Xanh thê", input: "https://chatxam.info/genre/xanh-the/", script: "gen.js" },
        { title: "Xuất quỹ - NTR", input: "https://chatxam.info/genre/xuat-quy-ntr/", script: "gen.js" },
        { title: "Xuyên không", input: "https://chatxam.info/genre/xuyen-khong/", script: "gen.js" },
    ]);
}