function execute() {
    return Response.success([
         {title: "Tuần Phiếu", input: "https://www.qidian.com/all/action0-update1-orderId9/?source=pc_jump", script: "gen.js"},
        {title: "Nguyệt Phiếu", input: "https://www.qidian.com/all/action0-update1-orderId10/?source=pc_jump", script: "gen.js"},
        {title: "30", input: "https://www.qidian.com/all/action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "30-50", input: "https://www.qidian.com/all/action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "50-100", input: "https://www.qidian.com/all/action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Võ Hiệp 30", input: "https://www.qidian.com/all/chanId2-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Võ Hiệp 50", input: "https://www.qidian.com/all/chanId2-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Võ Hiệp 100", input: "https://www.qidian.com/all/chanId2-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Tiên Hiệp 30", input: "https://www.qidian.com/all/chanId22-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Tiên Hiệp 50", input: "https://www.qidian.com/all/chanId22-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Tiên Hiệp 100", input: "https://www.qidian.com/all/chanId22-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Huyền Huyễn 30", input: "https://www.qidian.com/all/chanId21-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Huyền Huyễn 30-50", input: "https://www.qidian.com/all/chanId21-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Huyền Huyễn 50-100", input: "https://www.qidian.com/all/chanId21-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Khoa Huyễn 30", input: "https://www.qidian.com/all/chanId9-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Khoa Huyễn 30-50", input: "https://www.qidian.com/all/chanId9-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Khoa Huyễn 50-100", input: "https://www.qidian.com/all/chanId9-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Kỳ Ảo 30", input: "https://www.qidian.com/all/chanId1-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Kỳ Ảo 50", input: "https://www.qidian.com/all/chanId1-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Kỳ Ảo 100", input: "https://www.qidian.com/all/chanId1-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Trò Chơi 30", input: "https://www.qidian.com/all/chanId7-subCateId240-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Trò Chơi 30-50", input: "https://www.qidian.com/all/chanId7-subCateId240-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Trò Chơi 50-100", input: "https://www.qidian.com/all/chanId7-subCateId240-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Anime 30", input: "https://www.qidian.com/all/chanId12-subCateId60-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Anime 50", input: "https://www.qidian.com/all/chanId12-subCateId60-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Anime 100", input: "https://www.qidian.com/all/chanId12-subCateId60-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Chư Thiên 30", input: "https://www.qidian.com/all/chanId20109-subCateId60-action0-size1-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Chư Thiên 50", input: "https://www.qidian.com/all/chanId20109-subCateId60-action0-size2-update1-orderId11/?source=pc_jump", script: "gen.js"},
        {title: "Chư Thiên 100", input: "https://www.qidian.com/all/chanId20109-subCateId60-action0-size3-update1-orderId11/?source=pc_jump", script: "gen.js"},
    ]);
}