function execute() {
    return Response.success([
        { title: "Mỹ Thực",          input: "my-thuc",          script: "genrecontent.js" },
        { title: "Ngọt Sủng",        input: "ngot-sung",        script: "genrecontent.js" },
        { title: "Ngược",            input: "nguoc",            script: "genrecontent.js" },
        { title: "Nhân Thú",         input: "nhan-thu",         script: "genrecontent.js" },
        { title: "NP",               input: "np",               script: "genrecontent.js" },
        { title: "Nữ Tôn",           input: "nu-ton",           script: "genrecontent.js" },
        { title: "Phương Tây",       input: "phuong-tay",       script: "genrecontent.js" },
        { title: "SE",               input: "se",               script: "genrecontent.js" },
        { title: "Showbiz",          input: "showbiz",          script: "genrecontent.js" },
        { title: "Sinh Tồn",         input: "sinh-ton",         script: "genrecontent.js" },
        { title: "Song Trùng Sinh",  input: "song-trung-sinh",  script: "genrecontent.js" },
        { title: "Tận Thế",          input: "tan-the",          script: "genrecontent.js" },
        { title: "Tình Chị Em",      input: "tinh-chi-em",      script: "genrecontent.js" },
        { title: "Tinh Tế Cơ Giáp",  input: "tinh-te-co-giap",  script: "genrecontent.js" },
        { title: "Tình Thầy Trò",    input: "tinh-thay-tro",    script: "genrecontent.js" },
        { title: "Trâu Già Gặm Cỏ Non", input: "trau-gia-gam-co-non", script: "genrecontent.js" },
        { title: "Trinh Thám",       input: "trinh-tham",       script: "genrecontent.js" },
        { title: "Trùng Sinh",       input: "trung-sinh",       script: "genrecontent.js" },
        { title: "Truyện Ngắn",      input: "truyen-ngan",      script: "genrecontent.js" },
        { title: "Tự Sáng Tác",      input: "tu-sang-tac",      script: "genrecontent.js" },
        { title: "Vả Mặt",           input: "va-mat",           script: "genrecontent.js" },
        { title: "Vô Hạn Lưu",       input: "vo-han-luu",       script: "genrecontent.js" },
        { title: "Xuyên Không",      input: "xuyen-khong",      script: "genrecontent.js" },
        { title: "Xuyên Nhanh",      input: "xuyen-nhanh",      script: "genrecontent.js" },
        { title: "Xuyên Sách",       input: "xuyen-sach",       script: "genrecontent.js" },
        { title: "Zhihu",            input: "zhihu",            script: "genrecontent.js" },
        { title: "Cận Đại",          input: "can-dai",          script: "genrecontent.js" },
        { title: "Chiếm Hữu",        input: "chiem-huu",        script: "genrecontent.js" },
        { title: "Cổ Đại",           input: "co-dai",           script: "genrecontent.js" },
        { title: "Convert",          input: "convert",          script: "genrecontent.js" },
        { title: "Cung Đình Hầu Tước", input: "cung-dinh-hau-tuoc", script: "genrecontent.js" },
        { title: "Cưới Trước Yêu Sau", input: "cuoi-truoc-yeu-sau", script: "genrecontent.js" },
        { title: "Dịch Ái",          input: "dich-ai",          script: "genrecontent.js" },
        { title: "Đam Mỹ",           input: "dam-my",           script: "genrecontent.js" },
        { title: "Điền Văn",         input: "dien-van",         script: "genrecontent.js" },
        { title: "Đồng Nhân",        input: "dong-nhan",        script: "genrecontent.js" },
        { title: "Game Online",      input: "game-online",      script: "genrecontent.js" },
        { title: "Góc Nhìn Nam",     input: "goc-nhin-nam",     script: "genrecontent.js" },
        { title: "Góc Nhìn Nữ",      input: "goc-nhin-nu",      script: "genrecontent.js" },
        { title: "Gương Vỡ Không Lành", input: "guong-vo-khong-lanh", script: "genrecontent.js" },
        { title: "Gương Vỡ Lại Lành", input: "guong-vo-lai-lanh", script: "genrecontent.js" },
        { title: "H Văn",            input: "h-van",            script: "genrecontent.js" },
        { title: "Hài Hước",          input: "hai-huoc",          script: "genrecontent.js" },
        { title: "Hành Tinh Khác",   input: "hanh-tinh-khac",   script: "genrecontent.js" },
        { title: "HE",               input: "he",               script: "genrecontent.js" },
        { title: "Hệ Thống",         input: "he-thong",         script: "genrecontent.js" },
        { title: "Hiện Đại",         input: "hien-dai",         script: "genrecontent.js" },
        { title: "Học Đường",        input: "hoc-duong",        script: "genrecontent.js" },
        { title: "Huyền Huyễn",      input: "huyen-huyen",      script: "genrecontent.js" },
        { title: "Incest",           input: "incest",           script: "genrecontent.js" },
        { title: "Khoa Học Viễn Tưởng", input: "khoa-hoc-vien-tuong", script: "genrecontent.js" },
        { title: "Linh Dị",          input: "linh-di",          script: "genrecontent.js" }
    ]);
}
