function execute() {
    return Response.success([
        { title: "Bách Hợp", input: "/the-loai/bach-hop/", script: "gen.js" },
        { title: "Cung Đấu", input: "/the-loai/cung-dau/", script: "gen.js" },
        { title: "Đam Mỹ", input: "/the-loai/dam-my/", script: "gen.js" },
        { title: "Điền Văn", input: "/the-loai/dien-van/", script: "gen.js" },
        { title: "Đô Thị", input: "/the-loai/do-thi/", script: "gen.js" },
        { title: "Gia Đấu", input: "/the-loai/gia-dau/", script: "gen.js" },
        { title: "Hài Hước", input: "/the-loai/hai-hoc/", script: "gen.js" },
        { title: "Hiện Đại", input: "/the-loai/hien-dai/", script: "gen.js" },
        { title: "Hoàn Thành", input: "/the-loai/hoan-thanh/", script: "gen.js" },
        { title: "Học Đường", input: "/the-loai/hoc-duong/", script: "gen.js" },
        { title: "Huyền Huyễn", input: "/the-loai/huyen-huyen/", script: "gen.js" },
        { title: "Kiếm Hiệp", input: "/the-loai/kiem-hiep/", script: "gen.js" },
        { title: "Lịch sử", input: "/the-loai/lich-su/", script: "gen.js" },
        { title: "Mạt Thế", input: "/the-loai/mat-the/", script: "gen.js" },
        { title: "Ngôn Tình", input: "/the-loai/ngon-tinh/", script: "gen.js" },
        { title: "Ngược", input: "/the-loai/nguoc/", script: "gen.js" },
        { title: "Nữ Cường", input: "/the-loai/nu-cuong/", script: "gen.js" },
        { title: "Quân Nhân", input: "/the-loai/quan-nhan/", script: "gen.js" },
        { title: "Quân Sự", input: "/the-loai/quan-su/", script: "gen.js" },
        { title: "Quan Trường", input: "/the-loai/quan-truong/", script: "gen.js" },
        { title: "Sủng", input: "/the-loai/sung/", script: "gen.js" },
        { title: "Tất cả", input: "/the-loai/tat-ca/", script: "gen.js" },
        { title: "Tiên Hiệp", input: "/the-loai/mat-the/", script: "gen.js" },
        { title: "Tiểu Thuyết", input: "/the-loai/tien-hiep/", script: "gen.js" },
        { title: "Trọng Sinh", input: "/the-loai/tinh-yeu/", script: "gen.js" },
        { title: "Truyện Ma-Kinh Dị", input: "/the-loai/trong-sinh/", script: "gen.js" },
        { title: "Truyện Ngắn", input: "/the-loai/truyen-ma-kinh-di/", script: "gen.js" },
        { title: "Truyện Teen", input: "/the-loai/truyen-ngan/", script: "gen.js" },
        { title: "Võng Du", input: "/the-loai/truyen-teen/", script: "gen.js" },
        { title: "Xuyên Không", input: "/the-loai/xuyen-khong/", script: "gen.js" },
    ]);
}
