load("config.js");

function execute() {
    return Response.success([
        { title: "18+", input: "18", script: "genrecontent.js" },
        { title: "19+", input: "19", script: "genrecontent.js" },
        { title: "21+", input: "21", script: "genrecontent.js" },
        { title: "15+", input: "15", script: "genrecontent.js" },
        { title: "NSFW", input: "nsfw", script: "genrecontent.js" },
        { title: "Manhwa", input: "manhwa", script: "genrecontent.js" },
        { title: "Manga", input: "manga", script: "genrecontent.js" },
        { title: "Manhua", input: "manhua", script: "genrecontent.js" },
        { title: "Webtoon", input: "webtoon", script: "genrecontent.js" },
        { title: "Novel", input: "novel", script: "genrecontent.js" },
        { title: "Light Novel", input: "light-novel", script: "genrecontent.js" },
        { title: "Oneshot", input: "oneshot", script: "genrecontent.js" },
        { title: "Truyện Ngắn", input: "truyen-ngan", script: "genrecontent.js" },
        { title: "Tuyển Tập", input: "tuyen-tap", script: "genrecontent.js" },
        { title: "Action", input: "action", script: "genrecontent.js" },
        { title: "Comedy", input: "comedy", script: "genrecontent.js" },
        { title: "Drama", input: "drama", script: "genrecontent.js" },
        { title: "Fantasy", input: "fantasy", script: "genrecontent.js" },
        { title: "Horror", input: "horror", script: "genrecontent.js" },
        { title: "Magic", input: "magic", script: "genrecontent.js" },
        { title: "Romance", input: "romance", script: "genrecontent.js" },
        { title: "Romcom", input: "romcom", script: "genrecontent.js" },
        { title: "Shoujo", input: "shoujo", script: "genrecontent.js" },
        { title: "Slice Of Life", input: "slice-of-life", script: "genrecontent.js" },
        { title: "Isekai", input: "isekai", script: "genrecontent.js" },
        { title: "Harem", input: "harem", script: "genrecontent.js" },
        { title: "Dark Romance", input: "dark-romance", script: "genrecontent.js" },
        { title: "Học Đường", input: "hoc-duong", script: "genrecontent.js" },
        { title: "Thanh Xuân Vườn Trường", input: "thanh-xuan-vuon-truong", script: "genrecontent.js" },
        { title: "Lãng Mạn", input: "lang-man", script: "genrecontent.js" },
        { title: "Hài Lãng Mạn", input: "hai-lang-man", script: "genrecontent.js" },
        { title: "Hài Hước", input: "hai-huoc", script: "genrecontent.js" },
        { title: "Ngôn Tình", input: "ngon-tinh", script: "genrecontent.js" },
        { title: "Tình Cảm", input: "tinh-cam", script: "genrecontent.js" },
        { title: "Cảm Xúc", input: "cam-xuc", script: "genrecontent.js" },
        { title: "Ngọt", input: "ngot", script: "genrecontent.js" },
        { title: "Sủng", input: "sung", script: "genrecontent.js" },
        { title: "Chữa Lành", input: "chua-lanh", script: "genrecontent.js" },
        { title: "Cứu Rỗi", input: "cuu-roi", script: "genrecontent.js" },
        { title: "Sâu Lắng", input: "sau-lang", script: "genrecontent.js" },
        { title: "Vibe", input: "vibe", script: "genrecontent.js" },
        { title: "Cổ Đại", input: "co-dai", script: "genrecontent.js" },
        { title: "Cổ Trang", input: "co-trang", script: "genrecontent.js" },
        { title: "Âu Cổ", input: "au-co", script: "genrecontent.js" },
        { title: "Hiện Đại", input: "hien-dai", script: "genrecontent.js" },
        { title: "Đô Thị", input: "do-thi", script: "genrecontent.js" },
        { title: "Công Sở", input: "cong-so", script: "genrecontent.js" },
        { title: "Văn Phòng", input: "van-phong", script: "genrecontent.js" },
        { title: "Hoàng Gia", input: "hoang-gia", script: "genrecontent.js" },
        { title: "Chaebol", input: "chaebol", script: "genrecontent.js" },
        { title: "Tài Phiệt", input: "tai-phiet", script: "genrecontent.js" },
        { title: "Showbiz", input: "showbiz", script: "genrecontent.js" },
        { title: "Giới Giải Trí", input: "gioi-giai-tri", script: "genrecontent.js" },
        { title: "Idol", input: "idol", script: "genrecontent.js" },
        { title: "Chuyển Sinh", input: "chuyen-sinh", script: "genrecontent.js" },
        { title: "Tái Sinh", input: "tai-sinh", script: "genrecontent.js" },
        { title: "Trọng Sinh", input: "trong-sinh", script: "genrecontent.js" },
        { title: "Trùng Sinh", input: "trung-sinh", script: "genrecontent.js" },
        { title: "Xuyên Không", input: "xuyen-khong", script: "genrecontent.js" },
        { title: "Chuyển Thể", input: "chuyen-the", script: "genrecontent.js" },
        { title: "Chuyển Thể Từ Novel", input: "chuyen-the-tu-novel", script: "genrecontent.js" },
        { title: "Giả Tưởng", input: "gia-tuong", script: "genrecontent.js" },
        { title: "Viễn Tưởng", input: "vien-tuong", script: "genrecontent.js" },
        { title: "Huyền Bí", input: "huyen-bi", script: "genrecontent.js" },
        { title: "Phép Thuật", input: "phep-thuat", script: "genrecontent.js" },
        { title: "Phù Thủy", input: "phu-thuy", script: "genrecontent.js" },
        { title: "Siêu Năng Lực", input: "sieu-nang-luc", script: "genrecontent.js" },
        { title: "Kinh Dị", input: "kinh-di", script: "genrecontent.js" },
        { title: "Rùng Rợn", input: "rung-ron", script: "genrecontent.js" },
        { title: "Giật Gân", input: "giat-gan", script: "genrecontent.js" },
        { title: "Gây Sốc", input: "gay-soc", script: "genrecontent.js" },
        { title: "Kịch Tính", input: "kich-tinh", script: "genrecontent.js" },
        { title: "Chính Kịch", input: "chinh-kich", script: "genrecontent.js" },
        { title: "Tâm Lý", input: "tam-ly", script: "genrecontent.js" },
        { title: "Bi Kịch", input: "bi-kich", script: "genrecontent.js" },
        { title: "Ngược", input: "nguoc", script: "genrecontent.js" },
        { title: "Trinh Thám", input: "trinh-tham", script: "genrecontent.js" },
        { title: "Tội Phạm", input: "toi-pham", script: "genrecontent.js" },
        { title: "Giết Người", input: "giet-nguoi", script: "genrecontent.js" },
        { title: "Bạo Lực Học Đường", input: "bao-luc-hoc-duong", script: "genrecontent.js" },
        { title: "Thế Giới Ngầm", input: "the-gioi-ngam", script: "genrecontent.js" },
        { title: "Mafia", input: "mafia", script: "genrecontent.js" },
        { title: "Gangster", input: "gangster", script: "genrecontent.js" },
        { title: "Quân Nhân", input: "quan-nhan", script: "genrecontent.js" },
        { title: "Kỵ Sĩ", input: "ky-si", script: "genrecontent.js" },
        { title: "Thể Thao", input: "the-thao", script: "genrecontent.js" },
        { title: "Hệ Thống", input: "he-thong", script: "genrecontent.js" },
        { title: "Nữ Cường", input: "nu-cuong", script: "genrecontent.js" },
        { title: "Thánh Nữ", input: "thanh-nu", script: "genrecontent.js" },
        { title: "Trưởng Thành", input: "truong-thanh", script: "genrecontent.js" },
        { title: "Nặng Đô", input: "nang-do", script: "genrecontent.js" },
        { title: "Không Che", input: "khong-che", script: "genrecontent.js" },
        { title: "BDSM", input: "bdsm", script: "genrecontent.js" },
        { title: "NTR", input: "ntr", script: "genrecontent.js" },
        { title: "Cưỡng Bức", input: "cuong-buc", script: "genrecontent.js" },
        { title: "Phi Đạo Đức", input: "phi-dao-duc", script: "genrecontent.js" },
        { title: "Tình Yêu Cấm Đoán", input: "tinh-yeu-cam-doan", script: "genrecontent.js" },
        { title: "1x1", input: "1x1", script: "genrecontent.js" },
        { title: "3P", input: "3p", script: "genrecontent.js" },
        { title: "FWB", input: "fwb", script: "genrecontent.js" },
        { title: "Nữ x Nữ", input: "nu-x-nu", script: "genrecontent.js" },
        { title: "Dirty Talk", input: "dirty-talk", script: "genrecontent.js" },
        { title: "Trinh Nữ", input: "trinh-nu", script: "genrecontent.js" },
        { title: "Giam Cầm", input: "giam-cam", script: "genrecontent.js" },
        { title: "Chiếm Hữu", input: "chiem-huu", script: "genrecontent.js" },
        { title: "Yandere", input: "yandere", script: "genrecontent.js" },
        { title: "Tsundere", input: "tsundere", script: "genrecontent.js" },
        { title: "Bad Boy", input: "bad-boy", script: "genrecontent.js" },
        { title: "Good Boy", input: "good-boy", script: "genrecontent.js" },
        { title: "Trai Ngoan", input: "trai-ngoan", script: "genrecontent.js" },
        { title: "Bạn Thời Thơ Ấu", input: "ban-thoi-tho-au", script: "genrecontent.js" },
        { title: "Thanh Mai Trúc Mã", input: "thanh-mai-truc-ma", script: "genrecontent.js" },
        { title: "Mối Tình Đầu", input: "moi-tinh-dau", script: "genrecontent.js" },
        { title: "Yêu Đơn Phương", input: "yeu-don-phuong", script: "genrecontent.js" },
        { title: "Mối Tình Tay Ba", input: "moi-tinh-tay-ba", script: "genrecontent.js" },
        { title: "Bạn Bè > Người Yêu", input: "ban-be-nguoi-yeu", script: "genrecontent.js" },
        { title: "Cưới Trước Yêu Sau", input: "cuoi-truoc-yeu-sau", script: "genrecontent.js" },
        { title: "Ghét Trước Yêu Sau", input: "ghet-truoc-yeu-sau", script: "genrecontent.js" },
        { title: "Gương Vỡ Lại Lành", input: "guong-vo-lai-lanh", script: "genrecontent.js" },
        { title: "Hôn Nhân Hợp Đồng", input: "hon-nhan-hop-dong", script: "genrecontent.js" },
        { title: "Hợp Đồng Hẹn Hò", input: "hop-dong-hen-ho", script: "genrecontent.js" },
        { title: "Mối Quan Hệ Hợp Đồng", input: "moi-quan-he-hop-dong", script: "genrecontent.js" },
        { title: "Hôn Nhân Chính Trị", input: "hon-nhan-chinh-tri", script: "genrecontent.js" },
        { title: "Yêu Hận Tình Thù", input: "yeu-han-tinh-thu", script: "genrecontent.js" },
        { title: "Yêu Hận Đan Xen", input: "yeu-han-dan-xen", script: "genrecontent.js" },
        { title: "Ghen Tuông", input: "ghen-tuong", script: "genrecontent.js" },
        { title: "Hiểu Lầm", input: "hieu-lam", script: "genrecontent.js" },
        { title: "Xung Đột", input: "xung-dot", script: "genrecontent.js" },
        { title: "Báo Thù", input: "bao-thu", script: "genrecontent.js" },
        { title: "Trả Thù", input: "tra-thu", script: "genrecontent.js" },
        { title: "Truy Thê", input: "truy-the", script: "genrecontent.js" },
        { title: "Lọ Lem", input: "lo-lem", script: "genrecontent.js" },
        { title: "Mối Quan Hệ Tình Cảm Phức Tạp", input: "moi-quan-he-tinh-cam-phuc-tap", script: "genrecontent.js" },
        { title: "Ghét Của Nào Trời Trao Của Nấy", input: "ghet-cua-nao-troi-trao-cua-nay", script: "genrecontent.js" },
        { title: "Cơ Thể > Tim", input: "co-the-tim", script: "genrecontent.js" },
        { title: "Phi Công Trẻ Lái Máy Bay Bà Già", input: "phi-cong-tre-lai-may-bay-ba-gia", script: "genrecontent.js" },
        { title: "Khoảng Cách Tuổi Tác", input: "khoang-cach-tuoi-tac", script: "genrecontent.js" },
        { title: "Hàng Xóm", input: "hang-xom", script: "genrecontent.js" },
        { title: "Sống Chung", input: "song-chung", script: "genrecontent.js" },
        { title: "Mất Trí Nhớ", input: "mat-tri-nho", script: "genrecontent.js" },
        { title: "Gia Đình", input: "gia-dinh", script: "genrecontent.js" },
        { title: "Động Vật", input: "dong-vat", script: "genrecontent.js" },
        { title: "Người Thú", input: "nguoi-thu", script: "genrecontent.js" },
        { title: "Nhân Thú", input: "nhan-thu", script: "genrecontent.js" },
        { title: "Quái Vật", input: "quai-vat", script: "genrecontent.js" },
        { title: "Tiên Cá", input: "tien-ca", script: "genrecontent.js" },
        { title: "Zombie", input: "zombie", script: "genrecontent.js" },
        { title: "Ma Cà Rồng", input: "ma-ca-rong", script: "genrecontent.js" },
        { title: "Vampire", input: "vampire", script: "genrecontent.js" },
        { title: "Bối Cảnh Phương Tây", input: "boi-canh-phuong-tay", script: "genrecontent.js" }
    ]);
}
