load('config.js');
function execute() {
    return Response.success([
        {title: "Webnovel", input: BASE_URL + "/genre/Webnovel/", script: "gen.js"},
        {title: "Fantasy", input: BASE_URL + "/genre/Fantasy/", script: "gen.js"},
        {title: "Systemflow", input: BASE_URL + "/genre/Systemflow/", script: "gen.js"},
        {title: "Action", input: BASE_URL + "/genre/Action/", script: "gen.js"},
        {title: "Romance", input: BASE_URL + "/genre/Romance/", script: "gen.js"},
        {title: "Adventure", input: BASE_URL + "/genre/Adventure/", script: "gen.js"},
        {title: "Comedy", input: BASE_URL + "/genre/Comedy/", script: "gen.js"},
        {title: "Harem", input: BASE_URL + "/genre/Harem/", script: "gen.js"},
        {title: "Urban", input: BASE_URL + "/genre/Urban/", script: "gen.js"},
        {title: "Adult", input: BASE_URL + "/genre/Adult/", script: "gen.js"},
        {title: "Slice of Life", input: BASE_URL + "/genre/Slice+of+Life/", script: "gen.js"},
        {title: "Official Circles", input: BASE_URL + "/genre/Official+Circles/", script: "gen.js"},
        {title: "Science Fiction", input: BASE_URL + "/genre/Science+fiction/", script: "gen.js"},
        {title: "Drama", input: BASE_URL + "/genre/Drama/", script: "gen.js"},
        {title: "Mystery", input: BASE_URL + "/genre/Mystery/", script: "gen.js"},
        {title: "Supernatural", input: BASE_URL + "/genre/Supernatural/", script: "gen.js"},
        {title: "Reincarnation", input: BASE_URL + "/genre/Reincarnation/", script: "gen.js"},
        {title: "Game", input: BASE_URL + "/genre/Game/", script: "gen.js"},
        {title: "Mature", input: BASE_URL + "/genre/Mature/", script: "gen.js"},
        {title: "Martial Arts", input: BASE_URL + "/genre/Martial+Arts/", script: "gen.js"},
        {title: "Sci-fi", input: BASE_URL + "/genre/Sci-fi/", script: "gen.js"},
        {title: "Psychological", input: BASE_URL + "/genre/Psychological/", script: "gen.js"},
        {title: "School Life", input: BASE_URL + "/genre/School+Life/", script: "gen.js"},
        {title: "Eastern", input: BASE_URL + "/genre/Eastern/", script: "gen.js"},
        {title: "Xianxia", input: BASE_URL + "/genre/Xianxia/", script: "gen.js"},
        {title: "Historical", input: BASE_URL + "/genre/Historical/", script: "gen.js"},
        {title: "Other", input: BASE_URL + "/genre/Other/", script: "gen.js"},
        {title: "Tragedy", input: BASE_URL + "/genre/Tragedy/", script: "gen.js"},
        {title: "Xuanhuan", input: BASE_URL + "/genre/Xuanhuan/", script: "gen.js"},
        {title: "Smut", input: BASE_URL + "/genre/Smut/", script: "gen.js"},
        {title: "Ecchi", input: BASE_URL + "/genre/Ecchi/", script: "gen.js"},
        {title: "Shounen", input: BASE_URL + "/genre/Shounen/", script: "gen.js"},
        {title: "Josei", input: BASE_URL + "/genre/Josei/", script: "gen.js"},
        {title: "Yaoi", input: BASE_URL + "/genre/Yaoi/", script: "gen.js"},
        {title: "Seinen", input: BASE_URL + "/genre/Seinen/", script: "gen.js"},
        {title: "Horror", input: BASE_URL + "/genre/Horror/", script: "gen.js"},
        {title: "Fan-Fiction", input: BASE_URL + "/genre/Fan-Fiction/", script: "gen.js"},
        {title: "Gender Bender", input: BASE_URL + "/genre/Gender+Bender/", script: "gen.js"},
        {title: "Isekai", input: BASE_URL + "/genre/Isekai/", script: "gen.js"},
        {title: "Wuxia", input: BASE_URL + "/genre/Wuxia/", script: "gen.js"},
        {title: "Shoujo", input: BASE_URL + "/genre/Shoujo/", script: "gen.js"},
        {title: "Yuri", input: BASE_URL + "/genre/Yuri/", script: "gen.js"},
        {title: "Sports", input: BASE_URL + "/genre/Sports/", script: "gen.js"},
        {title: "Magic", input: BASE_URL + "/genre/Magic/", script: "gen.js"},
        {title: "Shounen Ai", input: BASE_URL + "/genre/Shounen+Ai/", script: "gen.js"},
        {title: "Mecha", input: BASE_URL + "/genre/Mecha/", script: "gen.js"},
        {title: "LitRPG", input: BASE_URL + "/genre/Litrpg/", script: "gen.js"},
        {title: "System", input: BASE_URL + "/genre/System/", script: "gen.js"},
        {title: "Shoujo Ai", input: BASE_URL + "/genre/Shoujo+Ai/", script: "gen.js"},
        {title: "Video games", input: BASE_URL + "/genre/Video+games/", script: "gen.js"},
        {title: "Anime & Comics", input: BASE_URL + "/genre/Anime+%26+comics/", script: "gen.js"},
        {title: "Magical Realism", input: BASE_URL + "/genre/Magical+realism/", script: "gen.js"},
        {title: "LGBT+", input: BASE_URL + "/genre/Lgbt%2B/", script: "gen.js"},
        {title: "Thriller", input: BASE_URL + "/genre/Thriller/", script: "gen.js"}
    ]);
}
